Repository newrelic/node-newrelic-koa, pull requests merged in 2020-07, with the labels that each got.

#34 Add repository prop to package.json
  package.json
  tests/versioned/package.json
Labels: risk:low, semver:patch

#49 Migrates CI to GitHub Actions.
  .github/workflows/ci-workflow.yml
  .travis.yml
Labels: risk:none, semver:patch

#50 Linting Nested `fn` Definition
  lib/router-instrumentation.js
Labels: risk:low, semver:patch

#52 Switch to Apache 2.0 license
  LICENSE
  package.json
Labels: ready for review, risk:low, semver:minor

#54 Update text to reference main
  NEWS.md
  README.md
Labels: risk:none, semver:patch

#53 Add copyright headers to source files
  index.js
  lib/instrumentation.js
  lib/route-instrumentation.js
  lib/router-instrumentation.js
  nr-hooks.js
  tests/unit/koa.tap.js
  tests/unit/newrelic.js
  tests/unit/route.tap.js
  tests/unit/router.tap.js
  tests/versioned/koa-route.tap.js
  tests/versioned/koa-router.tap.js
  tests/versioned/koa-v1.tap.js
  tests/versioned/koa.tap.js
  tests/versioned/newrelic.js
Labels: ready for review, risk:low, semver:minor

#55 Added an issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: ready for review, risk:none, semver:minor

#56 Updated PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review, risk:none, semver:minor

#51 Adds third party notices, bumps deps
  CONTRIBUTING.md
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: risk:low, semver:major

#59 Updates readme to standard template
  CONTRIBUTING.md
  README.md
Labels: risk:low, semver:patch

#62 Release v4.0.0
  NEWS.md
Labels: risk:low, semver:major

#63 Adds additional files to npm ignore.
  .npmignore
Labels: risk:low, semver:patch

#64 Adds additional dependency language to bottom of third party notices.
  THIRD_PARTY_NOTICES.md
Labels: risk:low, semver:patch

#66 Bumps node-test-utilities to ^4.0.0.
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: risk:low, semver:patch
