Repository newrelic/node-newrelic-koa, pull requests merged in 2021-07, with the labels that each got.

#88 Release/v6.0.0
  NEWS.md
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk:low, semver:major

#89 update files list to include versioned tests so they can run in main …
  package.json
Labels: semver:patch

#90 release 6.0.1
  NEWS.md
Labels: risk:low, semver:patch
