Repository newrelic/node-newrelic-koa, pull requests merged in 2024-04, with the labels that each got.

#177 test: Removed v1 versioned tests
  tests/versioned/koa-v1.tap.js
  tests/versioned/package.json
Labels: dev:tests

#181 ci: removed changelog.json file
  changelog.json
Labels: dev:automation

#182 ci: Removed `use_new_release` input from prepare release workflow
  .github/workflows/prepare-release.yml
Labels: dev:automation

#183 chore: Added package deprecation notice
  README.md
Labels: documentation
